name: build-and-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: "6.0.x"
  NODE_VERSION: "16"
  DOTNET_NOLOGO: true

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Tapper.csproj
        run: dotnet build ./src/Tapper/Tapper.csproj --no-restore

      - name: Test
        run: dotnet test --no-restore

      - name: Build Tapper.Generator.csproj
        run: dotnet build ./src/Tapper.Generator/Tapper.Generator.csproj --no-restore

      - name: Generate Code (json)
        run: dotnet run --project ./src/Tapper.Generator/Tapper.Generator.csproj --no-restore -- --project ./tests/Tapper.Tests.Server/Tapper.Tests.Server.csproj --output ./tests/TypeScriptTest/src/generated/json/

      - name: Generate Code (msgpack)
        run: dotnet run --project ./src/Tapper.Generator/Tapper.Generator.csproj --no-restore -- --project ./tests/Tapper.Tests.Server/Tapper.Tests.Server.csproj --output ./tests/TypeScriptTest/src/generated/msgpack --serializer messagepack --naming-style none --enum-naming-style none

      - name: Launch test server
        run: dotnet run --project ./tests/Tapper.Tests.Server/Tapper.Tests.Server.csproj --no-restore &

      - name: Install yarn
        run: npm install -g yarn

      - name: Yarn install
        run: yarn --cwd ./tests/TypeScriptTest/ install

      - name: Yarn Test
        run: yarn --cwd ./tests/TypeScriptTest/ test
